import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Generate the contents of a htap.ini file that configures PHP's
 * curl and OpenSSL extensions to trust the proxy CA certificate.
 *
 * PHP INI directives don't require quotes around values.
 */
export function generatePhpOverrideIni(caCertPath: string): string {
  return [
    "; Generated by htap — ensures PHP trusts the proxy CA certificate",
    `curl.cainfo=${caCertPath}`,
    `openssl.cafile=${caCertPath}`,
    "",
  ].join("\n");
}

/**
 * Write the htap.ini file to the given directory (typically
 * `.htap/php/`). Creates parent directories if needed.
 *
 * Returns the directory path (for use in PHP_INI_SCAN_DIR).
 */
export function writePhpOverride(outputDir: string, caCertPath: string): string {
  fs.mkdirSync(outputDir, { recursive: true });
  const iniPath = path.join(outputDir, "htap.ini");
  fs.writeFileSync(iniPath, generatePhpOverrideIni(caCertPath), "utf-8");
  return outputDir;
}
